spring:

    profiles:
        include: dev,prod
    application:
        name: piformer
    jpa:
        open-in-view: false
        properties:
            hibernate.jdbc.time_zone: UTC
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
                implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    freemarker:
        template-loader-path: classpath:/templates
        suffix: .ftl

server:
    servlet:
        session:
            cookie:
                http-only: true

