
logging:
    level:
        ROOT: DEBUG
        com.akulinski.piformer: DEBUG



spring:

    freemarker:
        template-loader-path: classpath:/templates
        suffix: .ftl

    profiles:
        active: dev
        include:
            - swagger

    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false
    jackson:
        serialization:
            indent-output: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: jdbc:h2:mem:testdb
        username: sa
        password:
        hikari:
            poolName: Hikari
            auto-commit: false
        driver-class-name: org.h2.Driver
        initialization-mode: always

    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database: H2
        show-sql: true
        properties:
            hibernate.id.new_generator_mappings: true
            hibernate.connection.provider_disables_autocommit: true
        hibernate:
            ddl-auto: create-drop
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard


server:
    port: 8080
