version: '2'
services:
    flatterservermonolith-app:
        image: akulinski/flatter-monolith
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATASOURCE_URL=jdbc:postgresql://flatterservermonolith-postgresql:5432/flatterservermonolith
            - JHIPSTER_SLEEP=40 # gives time for the JHipster Registry to boot before the application
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS=kafka
            - SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES=kafka
        ports:
            - 8080:8080
    flatterservermonolith-postgresql:
        extends:
            file: postgresql.yml
            service: flatterservermonolith-postgresql
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_TYPE=native
            - SPRING_CLOUD_CONFIG_SERVER_COMPOSITE_0_SEARCH_LOCATIONS=file:./central-config/docker-config/
    zookeeper:
        extends:
            file: kafka.yml
            service: zookeeper

networks:
    default:
        driver: bridge
