version: '2'
services:
    flatterservermonolith-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/flatterservermonolith/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=flatterservermonolith
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
networks:
    default:
        driver: bridge
